apiVersion: v1
kind: Service
metadata:
  name: devops-microservice-service
  labels:
    app: devops-microservice
spec:
  type: NodePort
  selector:
    app: devops-microservice
  ports:
  - name: http
    port: 80
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
  sessionAffinity: None