apiVersion: v2
name: mi-app
description: A Helm chart for DevOps microservice project
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - devops
  - microservice
  - kubernetes
maintainers:
  - name: Lalo
    email: lalo@devops.local